# Generated by Django 5.0.4 on 2026-03-02 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('label', models.CharField(help_text="e.g. 'Diabetes risk', 'Cardiac event risk'", max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='patients.patientprofile')),
            ],
        ),
    ]
